language: perl
install: export LDLOADLIBS=-lstdc++
perl:
  - "5.14"
  - "5.18"
  - "5.20"
branches:
  only:
    - master
    - stable
sudo: false
cache:
    - apt
addons:
  apt:
    sources:
    - boost-latest
    packages:
    - libboost-thread1.55-dev
    - libboost-system1.55-dev
    - libboost-filesystem1.55-dev
    - liblocal-lib-perl
before_script:
  - cpanm --quiet --notest --skip-satisfied git://github.com/codecov/codecov-perl@master
script:
  - perl ./Build.PL
  - cover -test
after_success:
  - cover -report codecov
