language: perl
before_install:
- openssl aes-256-cbc -K $encrypted_daaf322d08bf_key -iv $encrypted_daaf322d08bf_iv
  -in slic3r-upload.rsa.enc -out ~/slic3r-upload.rsa -d
install:
- export LDLOADLIBS=-lstdc++
- export BOOST_DIR=$HOME/boost_1_63_0
- export SLIC3R_STATIC=1
- export CXX=g++-4.9
- export CC=g++-4.9
- export WXDIR=$HOME/wx302
- source $HOME/perl5/perlbrew/etc/bashrc
script:
- bash package/linux/travis-setup.sh
- perlbrew switch slic3r-perl
- perl ./Build.PL
after_success:
- package/linux/make_archive.sh linux-x64
- package/deploy/sftp.sh linux ~/slic3r-upload.rsa *.bz2
branches:
  only:
  - master
  - xsgui
cache:
  apt: true
  directories:
  - "$HOME/cache"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - gcc-4.9
notifications:
  irc:
    channels:
    - chat.freenode.net#slic3r
    on_success: change
    on_failure: always
    use_notice: true
sudo: required
dist: trusty
env:
  matrix: 
  global:
  - secure: eEVRZNMv7FM6jrOU9iAFkDhWxFQ1WtHBEaObImcvtFUxy6vWSt3ehFFeTRouj3uHQAnbvUzziDyvPPm8/95alv5g/du8ML6YzzqKBKfazM0xQ7SF6R2DQL8lfFIp+RSV7T02byEP1f1g7Zva7xH9szIlDcSfU0pXW4KWbkBFMd8=
  - secure: hNd9SL178twKGKlx4xZsTuVzwKoMwhxIwqHuVFC3A4sdQXQysm14FbLootz6hri81tHuhjrx6owOjFQ24o8RIWfM9Rj3MnBZKfQK3HkB7gBoAkjIaJBgiYTjJBNbXGhQxG+Cvx6HqQVFkU/sLPkrvOiK0Z2/5wlNIjuMJ1gYAJI=
